<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>BlockBase</AssemblyName>
    <RootNamespace>BlockBaseNative</RootNamespace>
    <Version>6.0.0</Version>
    <FileVersion>6.0.0.0</FileVersion>
    <AssemblyVersion>6.0.0.0</AssemblyVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CmlLib.Core" Version="4.0.6" />
    <PackageReference Include="CmlLib.Core.Installer.Forge" Version="1.1.1" />
    <PackageReference Include="CmlLib.Core.Installer.NeoForge" Version="4.0.1" />
  </ItemGroup>
</Project>
